### ISSUE TITLE
Integrate Google cloud hosted Pubsub

### ISSUE THREAD

**Issue by rupeshpoojary** [featurehub-io/featurehub-helm#12]
Hi team,
we are integrating feature-hub into our ecosystem for all our product line, we wanted to integrate the google cloud hosted pub-sub into the feature-hub(hem chart) which we have deployed into our GKE cluster, currently the official documentation shows the implementation of a docker-compose based solution which has a pub-sub emulator as a container and passing the details of the pub-sub in the environment for edge and MR.

**How do i integrate/pass the details for pub-sub that is hosted in GCP, Please help me how do i integrate it to connect to google cloud pub-sub**

**Comment by rvowles** [comment]
Hi - I think we help you out in the Slack channel with this didn't we?

**Comment by rvowles** [comment]
All done!

**Comment by rvowles** [comment]
I have been reminded to add the link to the PR: https://github.com/featurehub-io/featurehub-helm/pull/20/files
