### ISSUE TITLE
Global Environment Vars using Secret

### ISSUE THREAD

**Issue by joelp172** [featurehub-io/featurehub-helm#14]
In order to deploy FeatureHub in [High Availability](https://github.com/featurehub-io/featurehub/discussions/790) mode securely, it is necessary to specify the NATS routes using [nats.urls](https://github.com/featurehub-io/featurehub-helm/blob/3fffce1442693ca1021202db20dc57b5f22407c0/helm/featurehub/values.yaml#L21) in the in environmentVars in the format `nats://user:password@url`.

This allows NATS clusters to communicate with one another using authentication (with the [authorization](https://docs.nats.io/running-a-nats-service/configuration/clustering/cluster_config) config set on each NATS cluster). However there is no way to set these env vars using a secret, meaning they are exposed in plain text.

The ability to set global.envFromSecret would allow the setting of nat.urls which include sensitive information.

**Comment by rvowles** [comment]
merged!
