### ISSUE TITLE
Parse error in deployment.yaml line 71

### ISSUE THREAD

**Issue by dsand1234** [featurehub-io/featurehub-helm#16]
Helm install failed: parse error at (featurehub/templates/management-repository/deployment.yaml:71): function "Values" not defined

The template has "Values" instead of ".Values"

**Comment by rvowles** [comment]
I wonde why the lint didn't pick that up?

**Comment by rvowles** [comment]
sorted! thanks for pointing this out, added hard code linting as well :)
