### ISSUE TITLE
Feature Request for initContainers option for the management-repository/deployment.yaml file 

### ISSUE THREAD

**Issue by jahosimafiah** [featurehub-io/featurehub-helm#2]
I would like to request that an initContainers section be added to the helm chart -> templates -> management-repository -> deployment.yaml file.

The use case is having a sidecar that can inject the backend credentials for the Postgres connection for the management-repository service to consume prior to the FeatureHub service starting and without needing to create a Kubernetes secret, or supply the credentials directly as an environment variable to be put in the configMap.

**Comment by rvowles** [comment]
I think you mean to add it to the values.yaml, which I can do.

**Comment by rvowles** [comment]
There is an associated PR which should allow you to insert any initContainers if you would like to check?

**Comment by jahosimafiah** [comment]
Thank you
