### ISSUE TITLE
podAnnotations . Allow special characters

### ISSUE THREAD

**Issue by Youka20** [featurehub-io/featurehub-helm#21]
Hi,
Firstly, I would like to thank you for the good work and for this wonderful system.

I have a little small issue when trying to deploy featurehub with customized root podAnnotation (with special characters example bellow), I get always errors like helm is not able to parse the chart values as string.  and this is because of the special characters in my podAnnotations.

`**podAnnotations**:
  Key1: value1
  Key2: '["value2"]'
  Key3: value3
`

I found a basic solution using quote function to allow special characters. code example bellow.
here a quick fix for that :
`
{{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
`

Another question I have,  why are you using the .Values.dacha.podAnnotations  for dacha deployment while for mr server and edge you use .Values.podAnnotations is there any reason behind this choice ?

thanks a lot
Youness

**Comment by rvowles** [comment]
Hey there @Youka20 ! Sorry, various folks have had a hand in the helm chart and I have been working on making it more consistent over the last month.
