### ISSUE TITLE
Add podLabels to Featurehub deployments

### ISSUE THREAD

**Issue by Youka20** [featurehub-io/featurehub-helm#28]
Hello Everyone,

Firstly, i would like to congratulate you for the great work and for this stable software.
In my organization, we are using a multi-tenant deployment and we laverage the podLabels to assign a deployment to a specific tenant.

And would like to know if it is possible to introduce the podLabels in the chart helm so we could customize them for our need.
Here a code sample for dacha deployment (could duplicate the same code for the MR Server and Edge deployment objects)

`labels:
        {{- include "featurehub.dacha.selectorLabels" . | nindent 8 }}
        
        {{- range $key, $value := .Values.dacha.podLabels }}
        {{ $key | quote }}: {{ $value | quote }}
        {{- end }}`
 
Thank you in advance for your response and keep the good work.
Youness Kassimi

**Comment by rvowles** [comment]
Could you please check the attached PR? Make sure it is what you are after.

**Comment by Youka20** [comment]
Hi @rvowles,

Thank you for the quick response. this is the exact functionality I am looking for. 

As for the Pull Request, to keep the chart consistent,  I suggest to not introduce the range function in the predefined template and use the array range directly inside the deployments files.

Otherwise you could introduce a template generic function as you did with "featurehub.podlabels" with a generic name but i thank this is quit an over-engineering in this stage.

```
{{- define "featurehub.keyValue" -}}
{{- range $key, $value := . -}}
{{ $key | quote }}: {{ $value | quote }}
{{- end -}}
{{- end -}}
```

Thank you a lot and waiting for your response.
Best Regards
Youness

**Comment by rvowles** [comment]
As soon as it is merged it's released?

**Comment by rvowles** [comment]
It looks like there was a silent failure in the Github action we use for releasing. I have made a change and it is now on ArtifactHub - sorry about the delay, I didn't realise.

**Comment by Youka20** [comment]
thank you for the quick fix.
very appreciated
