### ISSUE TITLE
appVersion not updated to latest Featurehub release

### ISSUE THREAD

**Issue by ilyatovbin-pp** [featurehub-io/featurehub-helm#6]
3.0.6 which is the latest version in the helm chart is pointing to appVersion:1.5.8 which is not the latest release.
I'm suggesting adding a Github Action or some other automated task that bumps the appVersion of this repo when creating a new release in the main featurehub repo.

Probably better do it in the featurehub repo and not here, but opening here since the issue is Helm related.

**Comment by rvowles** [comment]
just updated!
